### ISSUE TITLE
关于BtoA方向的训练

### ISSUE THREAD

**Issue by 2805413893** [Kid-Liet/Reg-GAN#11]
尊敬的作者您好，我已经完成了t1到t2模态的训练，也就是AtoB，但是注意到您的代码中没有关于t2生成t1的具体描述，想请问一下您该如何操作，感谢您的帮助，祝您工作顺利！

**Comment by Kid-Liet** [comment]
数据集改一下，将A和B交换吗并重新训练。RegGAN 本身只是单向的，并没有双向生成。
