### ISSUE TITLE
Hello, I have a question.

### ISSUE THREAD

**Issue by kimtaeuk-AI** [Kid-Liet/Reg-GAN#12]
I saw your good reg-net code.

But there's no code to run 'regTrainer.py', so can you upload it T^T?

I'd appreciate it if you upload it.

**Comment by Kid-Liet** [comment]
Hello，Set as follows and run "train.Py" stands for RegGan training.


![image](https://user-images.githubusercontent.com/52225942/156516393-846a4148-8b85-4902-8d16-e47a189af22b.png)
![image](https://user-images.githubusercontent.com/52225942/156516532-f9e66e89-c11d-4da4-8e5e-a523a6db5728.png)

**Comment by kimtaeuk-AI** [comment]
Thank you so much!
