### ISSUE TITLE
关于Ugat_Trainer以及其模型

### ISSUE THREAD

**Issue by 2805413893** [Kid-Liet/Reg-GAN#17]
尊敬的作者您好：
我在工程文件里注意到您没有公布ugat_trainer以及其模型的代码，请问您是否还保存这个模型的代码，希望您可以提供一些帮助。

**Comment by Kid-Liet** [comment]
没有保存了，映像中当时因为这个模型非常大，显存小一点的显卡都带不动。

**Comment by 2805413893** [comment]
感谢您的回复，还有一个问题，您的图像数据集使用的是单通道灰度图像，想请问一下您认为是否可以使用3通道的数据集呢，比如在自然图像上的验证，非常感谢您的帮助

**Comment by Kid-Liet** [comment]
你好，我认为可以试试自然图像。但太复杂的数据可能不太行，配准矫正难度太大

**Comment by 2805413893** [comment]
那就是类似于winter2summmer、day2night这种预先配对好的数据集，这种效果应该是比较好的吧，我是将这些数据集从png格式转换为了npy格式
