### ISSUE TITLE
关于unpaired datasets 的训练 

### ISSUE THREAD

**Issue by kkgoer** [Kid-Liet/Reg-GAN#18]
尊敬的作者，您好！我想请教一下文中所说的刚性配准具体用的哪个算法。“For unpaired datasets, we can conduct rigid registration ﬁrst in 3D space and then use RegGAN for training.” 这句话的意思是利用刚性配准尽可能的为源域图像找到配对图像后再用于reggan的训练吗？.

**Comment by Kid-Liet** [comment]
您好，文中并没有使用刚性算法，因为原始数据集本身就是对齐的。这里想表达的意思是实际使用不推荐unpaired的形式，即使不成对的数据，也可以利用刚性配准尽可能的为源域图像找到配对图像后再用于reggan的训练。
