### ISSUE TITLE
There are other architectures but not the main code I don't seem to see the code from the RegGAN 

### ISSUE THREAD

**Issue by ahmednebli** [Kid-Liet/Reg-GAN#19]

**Comment by Kid-Liet** [comment]
Hello，Set as follows and run "train.Py" stands for RegGan training.

![image](https://user-images.githubusercontent.com/52225942/174215110-2358d08c-a50c-452d-a00c-de158dc42a61.png)
image

![image](https://user-images.githubusercontent.com/52225942/174215138-75edf924-74b9-4376-b843-4ce0d59833dc.png)
