### ISSUE TITLE
数据集数量

### ISSUE THREAD

**Issue by Ban1-cmyk** [Kid-Liet/Reg-GAN#24]
作者您好，brats2018的训练集有285个病例，z轴数量为155，那么一共能产生44175个npy文件，但是文中提到训练集为8457，请问这个数据集是做了删减吗？或者是什么其它处理？麻烦您了，新手上路困难好多，如果您能告知一下我将万分感激。

**Comment by Kid-Liet** [comment]
您好，处理数据集的人已经离开了team，我也没有代码。但我可以从方向上进行建议：您需要尽可能保证目标模态数据分布的方差不要太大（例如要么都有噪声，要么都没有噪声，或者从统计上来清洗数据）。当方差过大时，目标就会不一致，生成效果就会有很大波动。

**Comment by Ban1-cmyk** [comment]
感谢您的及时回复♥♥♥
