### ISSUE TITLE
About the dataset used in paper.

### ISSUE THREAD

**Issue by ElegantLee** [Kid-Liet/Reg-GAN#7]
作者您好，方便提供一下您论文实验中使用的BraTS2018数据集吗？官方提供的数据为原始的nii数据，希望能直接在您使用的.npy数据集上直接做实验，这样能更好地复现。:relaxed:

**Comment by Kid-Liet** [comment]
好的，近期会放到网盘中

**Comment by Kid-Liet** [comment]
您的意思是，输入图像通道数为1会报错？ 这个很明显是输入图像与设置的通道数不相匹配造成的，线检查一下Yaml文件中，
image
yo有没有设置对

**Comment by Kid-Liet** [comment]
> > 刚刚尝试使用一个单通道的医学数据集，但是出现了以上的错误。调试发现，reg.py的torch.cat操作将两个tensor的通道拼接在一起，如果channel=3，cat后x的通道数为6就可以运行，但是现在channel=1，cat后x的通道数为2出现了第一张图片的错误。请问该修改哪里解决该问题呢？

您的意思是，输入图像通道数为1会报错？ 这个很明显是输入图像与设置的通道数不相匹配造成的，线检查一下Yaml文件中，
![image](https://user-images.githubusercontent.com/52225942/140638931-6c607224-0bbb-43c1-aa1f-941f26061c53.png)

有没有设置对

**Comment by ElegantLee** [comment]
> > > 刚刚尝试使用一个单通道的医学数据集，但是出现了以上的错误。调试发现，reg.py的torch.cat操作将两个tensor的通道拼接在一起，如果channel=3，cat后x的通道数为6就可以运行，但是现在channel=1，cat后x的通道数为2出现了第一张图片的错误。请问该修改哪里解决该问题呢？
> 
> 您的意思是，输入图像通道数为1会报错？ 这个很明显是输入图像与设置的通道数不相匹配造成的，线检查一下Yaml文件中， ![image](https://user-images.githubusercontent.com/52225942/140638931-6c607224-0bbb-43c1-aa1f-941f26061c53.png)
> 
> 有没有设置对

![image](https://user-images.githubusercontent.com/45191822/140638996-3de563a2-9fea-4098-bd49-e8eee1190f40.png)
配置文件没有问题。也就是说，只要配置文件中通道数设置没问题，就不会报错吗？那可能是我在修改了什么文件，我再检查一下。谢谢！

**Comment by Kid-Liet** [comment]
> > > > 刚刚尝试使用一个单通道的医学数据集，但是出现了以上的错误。调试发现，reg.py的torch.cat操作将两个tensor的通道拼接在一起，如果channel=3，cat后x的通道数为6就可以运行，但是现在channel=1，cat后x的通道数为2出现了第一张图片的错误。请问该修改哪里解决该问题呢？
> > 
> > 
> > 您的意思是，输入图像通道数为1会报错？ 这个很明显是输入图像与设置的通道数不相匹配造成的，线检查一下Yaml文件中， ![image](https://user-images.githubusercontent.com/52225942/140638931-6c607224-0bbb-43c1-aa1f-941f26061c53.png)
> > 有没有设置对
> 
> ![image](https://user-images.githubusercontent.com/45191822/140638996-3de563a2-9fea-4098-bd49-e8eee1190f40.png) 配置文件没有问题。也就是说，只要配置文件中通道数设置没问题，就不会报错吗？那可能是我在修改了什么文件，我再检查一下。谢谢！

![image](https://user-images.githubusercontent.com/52225942/140639102-f6925f75-fe1a-4730-84f9-57d273eaf17e.png)
我猜测是不是这个地方您是不是修改成了3造成的？

**Comment by Kid-Liet** [comment]
> ![image](https://user-images.githubusercontent.com/45191822/140638996-3de563a2-9fea-4098-bd49-e8eee1190f40.png) 配置文件没有问题。也就是说，只要配置文件中通道数设置没问题，就不会报错吗？那可能是我在修改了什么文件，我再检查一下。谢谢！

我修改一下代码，因为当时默认是在单通道数据集上做，有些地方会给使用RGB数据集的人造成一些麻烦。

**Comment by ElegantLee** [comment]
> 好的，近期会放到网盘
![image](https://user-images.githubusercontent.com/45191822/140638490-021edafd-167c-4f0d-bc61-602fa6807402.png)
![image](https://user-images.githubusercontent.com/45191822/140638540-cb93e91a-3207-41e3-8fd3-e6c2ec2bfbd7.png)
刚刚尝试使用一个单通道的医学数据集，但是出现了以上的错误。调试发现，reg.py的torch.cat操作将两个tensor的通道拼接在一起，如果channel=3，cat后x的通道数为6就可以运行，但是现在channel=1，cat后x的通道数为2出现了第一张图片的错误。请问该修改哪里解决该问题呢？

**Comment by Kid-Liet** [comment]
> 作者您好，方便提供一下您论文实验中使用的BraTS2018数据集吗？官方提供的数据为原始的nii数据，希望能直接在您使用的.npy数据集上直接做实验，这样能更好地复现。☺️

虽然是公开数据，但经过处理后的数据都进入了公司数据库，要公开需要走一些流程和申请，我们尽最大努力进行了公开，链接在首页，总共包含6526对处理好的数据。

**Comment by ElegantLee** [comment]
> > 作者您好，方便提供一下您论文实验中使用的BraTS2018数据集吗？官方提供的数据为原始的nii数据，希望能直接在您使用的.npy数据集上直接做实验，这样能更好地复现。☺️
> 
> 虽然是公开数据，但经过处理后的数据都进入了公司数据库，要公开需要走一些流程和申请，我们尽最大努力进行了公开，链接在首页，总共包含6526对处理好的数据。

麻烦您了，非常感谢！:handshake::handshake::handshake:
