### ISSUE TITLE
about how to process my own dataset for this project

### ISSUE THREAD

**Issue by 445193519** [Kid-Liet/Reg-GAN#8]
Can you please describe the features in the dataset processing process, I am training with my own dataset, but the dataset format is not correct. I've converted the png image to npy format, but I can't understand why the original dataset is two-dimensional

**Comment by Kid-Liet** [comment]
We use a single channel dataset by default. That is, the dimension of the original data is (W, H). If your default original data format is (1, W, H) or (3, W, H), you need to comment out 33 lines in utils.py.

![image](https://user-images.githubusercontent.com/52225942/147044510-1b158b2e-b962-42ec-a827-e8385d679616.png)
