### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by patricegaofei** [Kid-Liet/Reg-GAN#9]
Dear author,

I hope you are having a productive day. Congratulations on your great work, and thank you very much for making the source codes publicly accessible! As you stated in the environment requirements, one has to install Cuda 11.1 to be able to run the codes. Unfortunately, I am having an older Cuda version (10.0) on my server, and the codes do not work with this version. Besides, I am running the codes on a server that is being used by many people and I am not the Admin, which makes it quite impossible for me to upgrade the Cuda version. Please, is there any way to adjust the codes in such a way that they can be run on an environment with older Cuda version?

Thank you very much for your time and help!

With kind regards

**Comment by Kid-Liet** [comment]
Dear patricegaofei ：

Thank you for your attention! The main interface is only a reference environment, not necessary. You can use CUDA 10 with the appropriate version of pytorch. Generally speaking, it should be able to run directly. If you report any errors, you can paste the screenshot.

Best regards

**Comment by patricegaofei** [comment]
Dear Kid-Liet,
Thank you very much for your reply! I have been able to get the codes run.

Best regards
